name: Reusable Application Template Unit Tests

on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string
      os-list:
        required: false
        type: string
        default: '["macOS-latest", "ubuntu-latest"]'
        
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  tests:
    if: github.repository_owner == 'qiskit-community'
    name: ${{ matrix.os }}-tests-Python-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    env:
      DIR: ${{ inputs.dir }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: ["macOS-latest", "ubuntu-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install root dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements-dev.txt -c constraints.txt
        shell: bash

      - name: Install template-specific dependencies
        shell: bash
        run: |
          python -m pip install -U -r $DIR/requirements.txt -c constraints.txt

      - name: Run tests
        shell: bash
        run: |
          stestr --test-path $DIR/test run
