name: Hamiltonian Simulation Tests

on:
  push:
    branches: [main]
    paths:
      - 'physics/hamiltonian_simulation/**'
      - 'requirements-dev.txt'
      - 'requirements-e2e.txt'
      - 'tox.ini'
      
  pull_request:
    branches: [main]
    paths:
      - 'physics/hamiltonian_simulation/**'
      - 'requirements-dev.txt'
      - 'requirements-e2e.txt'
      - 'tox.ini'

jobs:
  call-tests:
    uses: ./.github/workflows/_unit-tests.yml
    with:
      dir: physics/hamiltonian_simulation
      os-list: '["macOS-latest", "ubuntu-latest", "windows-latest"]'
