name: AQC+Trotter Hamiltonian Dynamics Tests

on:
  push:
    branches: [main]
    paths:
      - 'physics/trotter_aqc_hamiltonian/**'
      - 'requirements-dev.txt'
      - 'requirements-e2e.txt'
      - 'tox.ini'

  pull_request:
    branches: [main]
    paths:
      - 'physics/trotter_aqc_hamiltonian/**'
      - 'requirements-dev.txt'
      - 'requirements-e2e.txt'
      - 'tox.ini'

jobs:
  call-tests:
    uses: ./.github/workflows/_unit-tests.yml
    with:
      dir: physics/trotter_aqc_hamiltonian
      os-list: '["macOS-latest", "ubuntu-latest"]'
